export type Course = {
  code: string
  title: string
  level: 'Undergraduate' | 'Graduate'
}

export type SubjectGroup = {
  subject: string
  name: string
  description: string
  courses: Course[]
}

export const courseCatalog: SubjectGroup[] = [
  {
    subject: 'CSC',
    name: 'Computer Science',
    description: 'Programming, algorithms, systems, artificial intelligence, and software development.',
    courses: [
      { code: 'CSC 241', title: 'Introduction to Computer Science I', level: 'Undergraduate' },
      { code: 'CSC 242', title: 'Introduction to Computer Science II', level: 'Undergraduate' },
      { code: 'CSC 243', title: 'Python Programming', level: 'Undergraduate' },
      { code: 'CSC 299', title: 'Discrete Mathematics for Computing', level: 'Undergraduate' },
      { code: 'CSC 300', title: 'Data Structures I', level: 'Undergraduate' },
      { code: 'CSC 301', title: 'Data Structures II', level: 'Undergraduate' },
      { code: 'CSC 321', title: 'Design and Analysis of Algorithms', level: 'Undergraduate' },
      { code: 'CSC 343', title: 'Operating Systems', level: 'Undergraduate' },
      { code: 'CSC 347', title: 'Concepts of Programming Languages', level: 'Undergraduate' },
      { code: 'CSC 373', title: 'Computer Systems I', level: 'Undergraduate' },
      { code: 'CSC 374', title: 'Computer Systems II', level: 'Undergraduate' },
      { code: 'CSC 380', title: 'Foundations of Artificial Intelligence', level: 'Undergraduate' },
      { code: 'CSC 401', title: 'Introduction to Programming', level: 'Graduate' },
      { code: 'CSC 402', title: 'Data Structures', level: 'Graduate' },
      { code: 'CSC 403', title: 'Data Structures II', level: 'Graduate' },
      { code: 'CSC 421', title: 'Applied Algorithms and Structures', level: 'Graduate' },
      { code: 'CSC 435', title: 'Distributed Systems I', level: 'Graduate' },
      { code: 'CSC 436', title: 'Distributed Systems II', level: 'Graduate' },
      { code: 'CSC 447', title: 'Concepts of Programming Languages', level: 'Graduate' },
      { code: 'CSC 453', title: 'Database Technologies', level: 'Graduate' },
      { code: 'CSC 480', title: 'Artificial Intelligence I', level: 'Graduate' },
      { code: 'CSC 481', title: 'Artificial Intelligence II', level: 'Graduate' },
      { code: 'CSC 482', title: 'Applied Machine Learning', level: 'Graduate' },
      { code: 'CSC 578', title: 'Neural Networks and Deep Learning', level: 'Graduate' },
    ],
  },
  {
    subject: 'SE',
    name: 'Software Engineering',
    description: 'Software design, testing, architecture, agile development, and project delivery.',
    courses: [
      { code: 'SE 325', title: 'Introduction to Software Engineering', level: 'Undergraduate' },
      { code: 'SE 333', title: 'Software Testing', level: 'Undergraduate' },
      { code: 'SE 350', title: 'Object-Oriented Software Development', level: 'Undergraduate' },
      { code: 'SE 352', title: 'Web Application Development', level: 'Undergraduate' },
      { code: 'SE 359', title: 'Agile Software Development', level: 'Undergraduate' },
      { code: 'SE 376', title: 'Software Project Management', level: 'Undergraduate' },
      { code: 'SE 430', title: 'Object-Oriented Modeling', level: 'Graduate' },
      { code: 'SE 433', title: 'Software Testing and Quality Assurance', level: 'Graduate' },
      { code: 'SE 450', title: 'Object-Oriented Software Development', level: 'Graduate' },
      { code: 'SE 452', title: 'Object-Oriented Enterprise Computing', level: 'Graduate' },
      { code: 'SE 456', title: 'Software Architecture', level: 'Graduate' },
      { code: 'SE 457', title: 'Service-Oriented Architecture', level: 'Graduate' },
      { code: 'SE 459', title: 'Agile Software Development', level: 'Graduate' },
      { code: 'SE 475', title: 'Software Project Management', level: 'Graduate' },
      { code: 'SE 491', title: 'Software Engineering Studio', level: 'Graduate' },
      { code: 'SE 525', title: 'DevOps Engineering', level: 'Graduate' },
    ],
  },
  {
    subject: 'IT',
    name: 'Information Technology',
    description: 'Web development, databases, applied programming, networking, and practical computing.',
    courses: [
      { code: 'IT 130', title: 'The Internet and the Web', level: 'Undergraduate' },
      { code: 'IT 202', title: 'Introduction to Human-Computer Interaction', level: 'Undergraduate' },
      { code: 'IT 204', title: 'Introduction to Generative AI', level: 'Undergraduate' },
      { code: 'IT 211', title: 'Introduction to Applied Programming', level: 'Undergraduate' },
      { code: 'IT 212', title: 'Applied Object-Oriented Programming', level: 'Undergraduate' },
      { code: 'IT 223', title: 'Data Analysis', level: 'Undergraduate' },
      { code: 'IT 231', title: 'Web Development I', level: 'Undergraduate' },
      { code: 'IT 232', title: 'Web Development II', level: 'Undergraduate' },
      { code: 'IT 238', title: 'Interactive Web Scripting', level: 'Undergraduate' },
      { code: 'IT 240', title: 'Introduction to Databases', level: 'Undergraduate' },
      { code: 'IT 313', title: 'Full Stack Web Development', level: 'Undergraduate' },
      { code: 'IT 320', title: 'Content Management Systems', level: 'Undergraduate' },
      { code: 'IT 330', title: 'User Interface Development', level: 'Undergraduate' },
      { code: 'IT 340', title: 'Cloud Infrastructure', level: 'Undergraduate' },
      { code: 'IT 411', title: 'Scripting for Information Technology', level: 'Graduate' },
      { code: 'IT 431', title: 'Web Architecture', level: 'Graduate' },
    ],
  },
  {
    subject: 'IS',
    name: 'Information Systems',
    description: 'Business systems, enterprise technology, databases, analytics, and information strategy.',
    courses: [
      { code: 'IS 201', title: 'Introduction to Information Systems', level: 'Undergraduate' },
      { code: 'IS 215', title: 'Analysis and Design Techniques', level: 'Undergraduate' },
      { code: 'IS 280', title: 'Communication for IT Professionals', level: 'Undergraduate' },
      { code: 'IS 360', title: 'Systems Analysis and Design', level: 'Undergraduate' },
      { code: 'IS 370', title: 'Database Management Systems', level: 'Undergraduate' },
      { code: 'IS 372', title: 'Enterprise Systems', level: 'Undergraduate' },
      { code: 'IS 421', title: 'Systems Analysis', level: 'Graduate' },
      { code: 'IS 430', title: 'Fundamentals of IT Project Management', level: 'Graduate' },
      { code: 'IS 444', title: 'Business Intelligence', level: 'Graduate' },
      { code: 'IS 467', title: 'Enterprise Architecture', level: 'Graduate' },
      { code: 'IS 500', title: 'Information Technology Leadership', level: 'Graduate' },
      { code: 'IS 556', title: 'Information Strategy and Management', level: 'Graduate' },
    ],
  },
  {
    subject: 'DSC',
    name: 'Data Science',
    description: 'Statistics, machine learning, data visualization, analytics, and data-driven decision making.',
    courses: [
      { code: 'DSC 323', title: 'Data Analysis and Regression', level: 'Undergraduate' },
      { code: 'DSC 324', title: 'Advanced Data Analysis', level: 'Undergraduate' },
      { code: 'DSC 333', title: 'Data Visualization', level: 'Undergraduate' },
      { code: 'DSC 341', title: 'Foundations of Data Science', level: 'Undergraduate' },
      { code: 'DSC 365', title: 'Data Mining', level: 'Undergraduate' },
      { code: 'DSC 383', title: 'Machine Learning', level: 'Undergraduate' },
      { code: 'DSC 401', title: 'Introduction to Data Science', level: 'Graduate' },
      { code: 'DSC 423', title: 'Data Analysis and Regression', level: 'Graduate' },
      { code: 'DSC 424', title: 'Advanced Data Analysis', level: 'Graduate' },
      { code: 'DSC 433', title: 'Data Visualization', level: 'Graduate' },
      { code: 'DSC 441', title: 'Fundamentals of Data Science', level: 'Graduate' },
      { code: 'DSC 465', title: 'Data Mining', level: 'Graduate' },
      { code: 'DSC 478', title: 'Programming Machine Learning Applications', level: 'Graduate' },
      { code: 'DSC 540', title: 'Advanced Machine Learning', level: 'Graduate' },
    ],
  },
  {
    subject: 'CSEC',
    name: 'Cybersecurity',
    description: 'Network security, cyber defense, digital forensics, secure systems, and ethical hacking.',
    courses: [
      { code: 'CSEC 201', title: 'Introduction to Cybersecurity', level: 'Undergraduate' },
      { code: 'CSEC 320', title: 'Host-Based Security', level: 'Undergraduate' },
      { code: 'CSEC 321', title: 'Network Security', level: 'Undergraduate' },
      { code: 'CSEC 340', title: 'Fundamentals of Information Assurance', level: 'Undergraduate' },
      { code: 'CSEC 378', title: 'Digital Forensics', level: 'Undergraduate' },
      { code: 'CSEC 380', title: 'Security Operations', level: 'Undergraduate' },
      { code: 'CSEC 421', title: 'Network Security', level: 'Graduate' },
      { code: 'CSEC 440', title: 'Information Security Management', level: 'Graduate' },
      { code: 'CSEC 450', title: 'Ethical Hacking', level: 'Graduate' },
      { code: 'CSEC 471', title: 'Digital Forensics Techniques', level: 'Graduate' },
      { code: 'CSEC 477', title: 'Cloud Security', level: 'Graduate' },
      { code: 'CSEC 520', title: 'Advanced Cyber Defense', level: 'Graduate' },
    ],
  },
  {
    subject: 'UXD',
    name: 'User Experience Design',
    description: 'User research, interaction design, prototyping, usability testing, and product design.',
    courses: [
      { code: 'UXD 101', title: 'Introduction to User Experience Design', level: 'Undergraduate' },
      { code: 'UXD 220', title: 'Prototyping and Implementation', level: 'Undergraduate' },
      { code: 'UXD 250', title: 'User Research Methods', level: 'Undergraduate' },
      { code: 'UXD 260', title: 'Design Principles', level: 'Undergraduate' },
      { code: 'UXD 270', title: 'Information Architecture', level: 'Undergraduate' },
      { code: 'UXD 310', title: 'Interaction Design', level: 'Undergraduate' },
      { code: 'UXD 430', title: 'Prototyping and Implementation', level: 'Graduate' },
      { code: 'UXD 440', title: 'Usability Evaluation Methods', level: 'Graduate' },
      { code: 'UXD 450', title: 'User Research Methods', level: 'Graduate' },
      { code: 'UXD 470', title: 'Information Architecture', level: 'Graduate' },
      { code: 'UXD 480', title: 'Product Design Studio', level: 'Graduate' },
    ],
  },
  {
    subject: 'PM',
    name: 'Project Management',
    description: 'Project planning, agile delivery, risk management, product strategy, and technical leadership.',
    courses: [
      { code: 'PM 330', title: 'Introduction to Project Management', level: 'Undergraduate' },
      { code: 'PM 340', title: 'Agile Project Methods', level: 'Undergraduate' },
      { code: 'PM 350', title: 'Project Planning and Control', level: 'Undergraduate' },
      { code: 'PM 410', title: 'Fundamentals of Project Management', level: 'Graduate' },
      { code: 'PM 420', title: 'Agile Methodologies', level: 'Graduate' },
      { code: 'PM 430', title: 'Project Risk Management', level: 'Graduate' },
      { code: 'PM 440', title: 'Product Strategy', level: 'Graduate' },
      { code: 'PM 450', title: 'Technical Leadership', level: 'Graduate' },
      { code: 'PM 470', title: 'Portfolio Management', level: 'Graduate' },
    ],
  },
  {
    subject: 'NET',
    name: 'Network Engineering',
    description: 'Computer networks, routing, cloud networking, network design, and infrastructure systems.',
    courses: [
      { code: 'NET 221', title: 'Network Fundamentals', level: 'Undergraduate' },
      { code: 'NET 322', title: 'Network Protocols', level: 'Undergraduate' },
      { code: 'NET 365', title: 'Data Communications', level: 'Undergraduate' },
      { code: 'NET 377', title: 'Wireless Networks', level: 'Undergraduate' },
      { code: 'NET 390', title: 'Cloud Networking', level: 'Undergraduate' },
      { code: 'NET 421', title: 'Network Design', level: 'Graduate' },
      { code: 'NET 450', title: 'Advanced Network Security', level: 'Graduate' },
      { code: 'NET 477', title: 'Wireless and Mobile Networks', level: 'Graduate' },
      { code: 'NET 560', title: 'Cloud Network Architecture', level: 'Graduate' },
    ],
  },
]
